---
abstract: 'I2C interface to PCA9685 16 channel 12 bit PWM Generator '
author:
  - 'Shantanu Bhadoria <shantanu at cpan dott org>'
build_requires:
  ExtUtils::MakeMaker: 0
  File::Find: 0
  File::Spec::Functions: 0
  File::Temp: 0
  List::Util: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300038, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Device-PCA9685
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
    - inc
  package:
    - DB
provides:
  Device::PCA9685:
    file: lib/Device/PCA9685.pm
    version: 0.001
  Device::PWMGenerator::PCA9685:
    file: lib/Device/PWMGenerator/PCA9685.pm
    version: 0.001
requires:
  Device::SMBus: 0
  Moose: 0
  POSIX: 0
  Time::HiRes: 0
  constant: 0
  perl: 5.010
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/shantanubhadoria/device-pca9685/issues
  homepage: https://metacpan.org/release/Device-PCA9685
  repository: git://github.com/shantanubhadoria/device-pca9685.git
version: 0.001
x_contributors:
  - 'Shantanu <shantanu@cpan.org>'
  - 'Shantanu Bhadoria <shantanu@cpan.org>'
